server:
  port: 8092

spring:
  profiles:
     active: native
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://gitee.com/helixin/spring-cloud-config.git
#          searchPaths: "local"
#      label: "master"



