server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${r"${"}spring.application.name}:${r"${"}spring.cloud.client.ipAddress}:${r"${"}spring.application.instance_id:${r"${"}server.port}}
    ip-address: localhost

spring:
  application:
    name: pps-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/helixin/spring-cloud-config.git
          searchPaths: "local"
      label: "master"
#security:
#  basic:
#    enabled: false
#  user:
#    name: root
#    password: booszy