server:
  port: 8762

spring:
  application:
    name: eureka-server
  output:
    ansi:
      enabled: always

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
  client:
    register-with-eureka: true #是否将自身注册
    fetch-registry: false #如果为true，启动时报警.
    serviceUrl:
      defaultZone: http://${r'${'}eureka.instance.hostname}:8762/eureka/