config:
  domain:
wx:
  js_appid: wxdac7ad67dd4a1044
  js_app_secret: 659dcfdb1cd4a5ff2a2071b89c8949f5

spring:
  auto:
    openurl: true # 是否打开，想打开下边就写true
  web:
    loginurl: http://localhost:8762/swagger-ui.html # 浏览器自动打开swagger-ui可视界面
    browserExcutePath: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" # 选择浏览器的路径

# 七牛云账号与配置
qiniu:
  # AccessKey|AK
  AK:
  # SecretKey|SK
  SK:
  # 空间名称
  bucket_name:
  # 空间域名
  service: pra7fn3tm.bkt.clouddn.com
  # 上传文件的临时目录
  upload_temp_dir: upload

logging:
  level:
    root: debug
    sun.rmi: warn
    java.sql.Connection: info
    java.sql.Statement: info
    java.sql.PreparedStatement: info
    javax.activation: info
    org.mybatis.spring: info
    com.github: error
    org.apache: warn
    org.apache.tomcat: info
    org.apache.ibatis: info
    org.hibernate: error
    org.jboss.logging: error
    org.springframework: warn
    org.springframework.boot: info
    springfox.documentation: warn
